/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as DevelopersIndexRouteImport } from './routes/developers/index'
import { Route as DevelopersApiRouteImport } from './routes/developers/api'
import { Route as DevelopersApiKeysRouteImport } from './routes/developers/api-keys'
import { Route as DevelopersDocsRouteImport } from './routes/developers/docs'
import { Route as DevelopersExplorerRouteImport } from './routes/developers/explorer'
import { Route as DevelopersSandboxRouteImport } from './routes/developers/sandbox'
import { Route as DevelopersSdkRouteImport } from './routes/developers/sdk'
import { Route as DevelopersUsageRouteImport } from './routes/developers/usage'
import { Route as DevelopersWebhooksRouteImport } from './routes/developers/webhooks'
import { Route as FirewallsIndexRouteImport } from './routes/firewalls/index'
import { Route as FirewallsFirewallIdRouteImport } from './routes/firewalls/$firewallId'
import { Route as FirewallsNewRouteImport } from './routes/firewalls/new'
import { Route as OutcomesExecutionIdRouteImport } from './routes/outcomes/$executionId'
import { Route as ProofsIndexRouteImport } from './routes/proofs/index'
import { Route as ProofsProofIdRouteImport } from './routes/proofs/$proofId'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents/$agentId/index'
import { Route as AgentsAgentIdActivityRouteImport } from './routes/agents/$agentId/activity'
import { Route as AgentsAgentIdFirewallRouteImport } from './routes/agents/$agentId/firewall'
import { Route as AgentsAgentIdOutcomesRouteImport } from './routes/agents/$agentId/outcomes'
import { Route as AgentsAgentIdProofsRouteImport } from './routes/agents/$agentId/proofs'
import { Route as AgentsAgentIdReputationRouteImport } from './routes/agents/$agentId/reputation'
import { Route as ApiAgentsIndexRouteImport } from './routes/api/agents/index'
import { Route as ApiAgentsSearchRouteImport } from './routes/api/agents/search'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFirewallsIndexRouteImport } from './routes/api/firewalls/index'
import { Route as ApiProofsIndexRouteImport } from './routes/api/proofs/index'
import { Route as ApiReputationIndexRouteImport } from './routes/api/reputation/index'
import { Route as DevelopersDocsDemoRouteImport } from './routes/developers/docs.demo'
import { Route as ApiAgentsAgentIdIndexRouteImport } from './routes/api/agents/$agentId/index'
import { Route as ApiAgentsAgentIdActivityRouteImport } from './routes/api/agents/$agentId/activity'
import { Route as ApiAgentsAgentIdEventsRouteImport } from './routes/api/agents/$agentId/events'
import { Route as ApiAgentsAgentIdFirewallRouteImport } from './routes/api/agents/$agentId/firewall'
import { Route as ApiAgentsAgentIdOutcomesRouteImport } from './routes/api/agents/$agentId/outcomes'
import { Route as ApiAgentsAgentIdProofsRouteImport } from './routes/api/agents/$agentId/proofs'
import { Route as ApiAgentsAgentIdReputationRouteImport } from './routes/api/agents/$agentId/reputation'
import { Route as ApiAgentsOwnerAddressRouteImport } from './routes/api/agents/owner/$address'
import { Route as ApiFirewallsFirewallIdIndexRouteImport } from './routes/api/firewalls/$firewallId/index'
import { Route as ApiFirewallsFirewallIdExecutionsRouteImport } from './routes/api/firewalls/$firewallId/executions'
import { Route as ApiFirewallsFirewallIdFunctionsRouteImport } from './routes/api/firewalls/$firewallId/functions'
import { Route as ApiFirewallsFirewallIdPolicyRouteImport } from './routes/api/firewalls/$firewallId/policy'
import { Route as ApiFirewallsFirewallIdProofsRouteImport } from './routes/api/firewalls/$firewallId/proofs'
import { Route as ApiFirewallsFirewallIdTargetsRouteImport } from './routes/api/firewalls/$firewallId/targets'
import { Route as ApiOutcomesExecutionIdIndexRouteImport } from './routes/api/outcomes/$executionId/index'
import { Route as ApiOutcomesExecutionIdAnchorRouteImport } from './routes/api/outcomes/$executionId/anchor'
import { Route as ApiOutcomesExecutionIdEvidenceRouteImport } from './routes/api/outcomes/$executionId/evidence'
import { Route as ApiOutcomesExecutionIdVerifyRouteImport } from './routes/api/outcomes/$executionId/verify'
import { Route as ApiProofsExecutionIdIndexRouteImport } from './routes/api/proofs/$executionId/index'
import { Route as ApiProofsExecutionIdAnchorRouteImport } from './routes/api/proofs/$executionId/anchor'
import { Route as ApiProofsExecutionIdVerificationRouteImport } from './routes/api/proofs/$executionId/verification'
import { Route as ApiProofsExecutionIdVerifyRouteImport } from './routes/api/proofs/$executionId/verify'
import { Route as ApiV1AgentsIndexRouteImport } from './routes/api/v1/agents/index'
import { Route as ApiV1AgentsAgentIdRouteImport } from './routes/api/v1/agents/$agentId'
import { Route as ApiV1ExecutionsExecutionIdRouteImport } from './routes/api/v1/executions/$executionId'
import { Route as ApiV1FirewallsIndexRouteImport } from './routes/api/v1/firewalls/index'
import { Route as ApiV1WebhooksIndexRouteImport } from './routes/api/v1/webhooks/index'
import { Route as ApiV1WebhooksWebhookIdRouteImport } from './routes/api/v1/webhooks/$webhookId'
import { Route as ApiV1FirewallsFirewallIdIndexRouteImport } from './routes/api/v1/firewalls/$firewallId/index'
import { Route as ApiV1FirewallsFirewallIdExecuteRouteImport } from './routes/api/v1/firewalls/$firewallId/execute'
import { Route as ApiV1FirewallsFirewallIdFunctionsRouteImport } from './routes/api/v1/firewalls/$firewallId/functions'
import { Route as ApiV1FirewallsFirewallIdTargetsRouteImport } from './routes/api/v1/firewalls/$firewallId/targets'
import { Route as ApiV1OutcomesExecutionIdIndexRouteImport } from './routes/api/v1/outcomes/$executionId/index'
import { Route as ApiV1OutcomesExecutionIdVerifyRouteImport } from './routes/api/v1/outcomes/$executionId/verify'
import { Route as ApiV1ProofsExecutionIdIndexRouteImport } from './routes/api/v1/proofs/$executionId/index'
import { Route as ApiV1ProofsExecutionIdVerifyRouteImport } from './routes/api/v1/proofs/$executionId/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersApiRoute = DevelopersApiRouteImport.update({
  id: '/developers/api',
  path: '/developers/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersApiKeysRoute = DevelopersApiKeysRouteImport.update({
  id: '/developers/api-keys',
  path: '/developers/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersDocsRoute = DevelopersDocsRouteImport.update({
  id: '/developers/docs',
  path: '/developers/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersExplorerRoute = DevelopersExplorerRouteImport.update({
  id: '/developers/explorer',
  path: '/developers/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersSandboxRoute = DevelopersSandboxRouteImport.update({
  id: '/developers/sandbox',
  path: '/developers/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersSdkRoute = DevelopersSdkRouteImport.update({
  id: '/developers/sdk',
  path: '/developers/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersUsageRoute = DevelopersUsageRouteImport.update({
  id: '/developers/usage',
  path: '/developers/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersWebhooksRoute = DevelopersWebhooksRouteImport.update({
  id: '/developers/webhooks',
  path: '/developers/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallsIndexRoute = FirewallsIndexRouteImport.update({
  id: '/firewalls/',
  path: '/firewalls/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallsFirewallIdRoute = FirewallsFirewallIdRouteImport.update({
  id: '/firewalls/$firewallId',
  path: '/firewalls/$firewallId',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallsNewRoute = FirewallsNewRouteImport.update({
  id: '/firewalls/new',
  path: '/firewalls/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesExecutionIdRoute = OutcomesExecutionIdRouteImport.update({
  id: '/outcomes/$executionId',
  path: '/outcomes/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofsIndexRoute = ProofsIndexRouteImport.update({
  id: '/proofs/',
  path: '/proofs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofsProofIdRoute = ProofsProofIdRouteImport.update({
  id: '/proofs/$proofId',
  path: '/proofs/$proofId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdActivityRoute = AgentsAgentIdActivityRouteImport.update({
  id: '/agents/$agentId/activity',
  path: '/agents/$agentId/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdFirewallRoute = AgentsAgentIdFirewallRouteImport.update({
  id: '/agents/$agentId/firewall',
  path: '/agents/$agentId/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdOutcomesRoute = AgentsAgentIdOutcomesRouteImport.update({
  id: '/agents/$agentId/outcomes',
  path: '/agents/$agentId/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdProofsRoute = AgentsAgentIdProofsRouteImport.update({
  id: '/agents/$agentId/proofs',
  path: '/agents/$agentId/proofs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdReputationRoute = AgentsAgentIdReputationRouteImport.update({
  id: '/agents/$agentId/reputation',
  path: '/agents/$agentId/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIndexRoute = ApiAgentsIndexRouteImport.update({
  id: '/api/agents/',
  path: '/api/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSearchRoute = ApiAgentsSearchRouteImport.update({
  id: '/api/agents/search',
  path: '/api/agents/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirewallsIndexRoute = ApiFirewallsIndexRouteImport.update({
  id: '/api/firewalls/',
  path: '/api/firewalls/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProofsIndexRoute = ApiProofsIndexRouteImport.update({
  id: '/api/proofs/',
  path: '/api/proofs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReputationIndexRoute = ApiReputationIndexRouteImport.update({
  id: '/api/reputation/',
  path: '/api/reputation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersDocsDemoRoute = DevelopersDocsDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => DevelopersDocsRoute,
} as any)
const ApiAgentsAgentIdIndexRoute = ApiAgentsAgentIdIndexRouteImport.update({
  id: '/api/agents/$agentId/',
  path: '/api/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsAgentIdActivityRoute =
  ApiAgentsAgentIdActivityRouteImport.update({
    id: '/api/agents/$agentId/activity',
    path: '/api/agents/$agentId/activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentsAgentIdEventsRoute = ApiAgentsAgentIdEventsRouteImport.update({
  id: '/api/agents/$agentId/events',
  path: '/api/agents/$agentId/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsAgentIdFirewallRoute =
  ApiAgentsAgentIdFirewallRouteImport.update({
    id: '/api/agents/$agentId/firewall',
    path: '/api/agents/$agentId/firewall',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentsAgentIdOutcomesRoute =
  ApiAgentsAgentIdOutcomesRouteImport.update({
    id: '/api/agents/$agentId/outcomes',
    path: '/api/agents/$agentId/outcomes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentsAgentIdProofsRoute = ApiAgentsAgentIdProofsRouteImport.update({
  id: '/api/agents/$agentId/proofs',
  path: '/api/agents/$agentId/proofs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsAgentIdReputationRoute =
  ApiAgentsAgentIdReputationRouteImport.update({
    id: '/api/agents/$agentId/reputation',
    path: '/api/agents/$agentId/reputation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentsOwnerAddressRoute = ApiAgentsOwnerAddressRouteImport.update({
  id: '/api/agents/owner/$address',
  path: '/api/agents/owner/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirewallsFirewallIdIndexRoute =
  ApiFirewallsFirewallIdIndexRouteImport.update({
    id: '/api/firewalls/$firewallId/',
    path: '/api/firewalls/$firewallId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirewallsFirewallIdExecutionsRoute =
  ApiFirewallsFirewallIdExecutionsRouteImport.update({
    id: '/api/firewalls/$firewallId/executions',
    path: '/api/firewalls/$firewallId/executions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirewallsFirewallIdFunctionsRoute =
  ApiFirewallsFirewallIdFunctionsRouteImport.update({
    id: '/api/firewalls/$firewallId/functions',
    path: '/api/firewalls/$firewallId/functions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirewallsFirewallIdPolicyRoute =
  ApiFirewallsFirewallIdPolicyRouteImport.update({
    id: '/api/firewalls/$firewallId/policy',
    path: '/api/firewalls/$firewallId/policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirewallsFirewallIdProofsRoute =
  ApiFirewallsFirewallIdProofsRouteImport.update({
    id: '/api/firewalls/$firewallId/proofs',
    path: '/api/firewalls/$firewallId/proofs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFirewallsFirewallIdTargetsRoute =
  ApiFirewallsFirewallIdTargetsRouteImport.update({
    id: '/api/firewalls/$firewallId/targets',
    path: '/api/firewalls/$firewallId/targets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOutcomesExecutionIdIndexRoute =
  ApiOutcomesExecutionIdIndexRouteImport.update({
    id: '/api/outcomes/$executionId/',
    path: '/api/outcomes/$executionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOutcomesExecutionIdAnchorRoute =
  ApiOutcomesExecutionIdAnchorRouteImport.update({
    id: '/api/outcomes/$executionId/anchor',
    path: '/api/outcomes/$executionId/anchor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOutcomesExecutionIdEvidenceRoute =
  ApiOutcomesExecutionIdEvidenceRouteImport.update({
    id: '/api/outcomes/$executionId/evidence',
    path: '/api/outcomes/$executionId/evidence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOutcomesExecutionIdVerifyRoute =
  ApiOutcomesExecutionIdVerifyRouteImport.update({
    id: '/api/outcomes/$executionId/verify',
    path: '/api/outcomes/$executionId/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProofsExecutionIdIndexRoute =
  ApiProofsExecutionIdIndexRouteImport.update({
    id: '/api/proofs/$executionId/',
    path: '/api/proofs/$executionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProofsExecutionIdAnchorRoute =
  ApiProofsExecutionIdAnchorRouteImport.update({
    id: '/api/proofs/$executionId/anchor',
    path: '/api/proofs/$executionId/anchor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProofsExecutionIdVerificationRoute =
  ApiProofsExecutionIdVerificationRouteImport.update({
    id: '/api/proofs/$executionId/verification',
    path: '/api/proofs/$executionId/verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProofsExecutionIdVerifyRoute =
  ApiProofsExecutionIdVerifyRouteImport.update({
    id: '/api/proofs/$executionId/verify',
    path: '/api/proofs/$executionId/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AgentsIndexRoute = ApiV1AgentsIndexRouteImport.update({
  id: '/api/v1/agents/',
  path: '/api/v1/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AgentsAgentIdRoute = ApiV1AgentsAgentIdRouteImport.update({
  id: '/api/v1/agents/$agentId',
  path: '/api/v1/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExecutionsExecutionIdRoute =
  ApiV1ExecutionsExecutionIdRouteImport.update({
    id: '/api/v1/executions/$executionId',
    path: '/api/v1/executions/$executionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FirewallsIndexRoute = ApiV1FirewallsIndexRouteImport.update({
  id: '/api/v1/firewalls/',
  path: '/api/v1/firewalls/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WebhooksIndexRoute = ApiV1WebhooksIndexRouteImport.update({
  id: '/api/v1/webhooks/',
  path: '/api/v1/webhooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WebhooksWebhookIdRoute = ApiV1WebhooksWebhookIdRouteImport.update({
  id: '/api/v1/webhooks/$webhookId',
  path: '/api/v1/webhooks/$webhookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FirewallsFirewallIdIndexRoute =
  ApiV1FirewallsFirewallIdIndexRouteImport.update({
    id: '/api/v1/firewalls/$firewallId/',
    path: '/api/v1/firewalls/$firewallId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FirewallsFirewallIdExecuteRoute =
  ApiV1FirewallsFirewallIdExecuteRouteImport.update({
    id: '/api/v1/firewalls/$firewallId/execute',
    path: '/api/v1/firewalls/$firewallId/execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FirewallsFirewallIdFunctionsRoute =
  ApiV1FirewallsFirewallIdFunctionsRouteImport.update({
    id: '/api/v1/firewalls/$firewallId/functions',
    path: '/api/v1/firewalls/$firewallId/functions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FirewallsFirewallIdTargetsRoute =
  ApiV1FirewallsFirewallIdTargetsRouteImport.update({
    id: '/api/v1/firewalls/$firewallId/targets',
    path: '/api/v1/firewalls/$firewallId/targets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OutcomesExecutionIdIndexRoute =
  ApiV1OutcomesExecutionIdIndexRouteImport.update({
    id: '/api/v1/outcomes/$executionId/',
    path: '/api/v1/outcomes/$executionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1OutcomesExecutionIdVerifyRoute =
  ApiV1OutcomesExecutionIdVerifyRouteImport.update({
    id: '/api/v1/outcomes/$executionId/verify',
    path: '/api/v1/outcomes/$executionId/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProofsExecutionIdIndexRoute =
  ApiV1ProofsExecutionIdIndexRouteImport.update({
    id: '/api/v1/proofs/$executionId/',
    path: '/api/v1/proofs/$executionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProofsExecutionIdVerifyRoute =
  ApiV1ProofsExecutionIdVerifyRouteImport.update({
    id: '/api/v1/proofs/$executionId/verify',
    path: '/api/v1/proofs/$executionId/verify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/agents/new': typeof AgentsNewRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/api-keys': typeof DevelopersApiKeysRoute
  '/developers/docs': typeof DevelopersDocsRouteWithChildren
  '/developers/explorer': typeof DevelopersExplorerRoute
  '/developers/sandbox': typeof DevelopersSandboxRoute
  '/developers/sdk': typeof DevelopersSdkRoute
  '/developers/usage': typeof DevelopersUsageRoute
  '/developers/webhooks': typeof DevelopersWebhooksRoute
  '/firewalls/$firewallId': typeof FirewallsFirewallIdRoute
  '/firewalls/new': typeof FirewallsNewRoute
  '/outcomes/$executionId': typeof OutcomesExecutionIdRoute
  '/proofs/$proofId': typeof ProofsProofIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/firewalls/': typeof FirewallsIndexRoute
  '/proofs/': typeof ProofsIndexRoute
  '/agents/$agentId/activity': typeof AgentsAgentIdActivityRoute
  '/agents/$agentId/firewall': typeof AgentsAgentIdFirewallRoute
  '/agents/$agentId/outcomes': typeof AgentsAgentIdOutcomesRoute
  '/agents/$agentId/proofs': typeof AgentsAgentIdProofsRoute
  '/agents/$agentId/reputation': typeof AgentsAgentIdReputationRoute
  '/api/agents/search': typeof ApiAgentsSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/developers/docs/demo': typeof DevelopersDocsDemoRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
  '/api/agents/': typeof ApiAgentsIndexRoute
  '/api/firewalls/': typeof ApiFirewallsIndexRoute
  '/api/proofs/': typeof ApiProofsIndexRoute
  '/api/reputation/': typeof ApiReputationIndexRoute
  '/api/agents/$agentId/activity': typeof ApiAgentsAgentIdActivityRoute
  '/api/agents/$agentId/events': typeof ApiAgentsAgentIdEventsRoute
  '/api/agents/$agentId/firewall': typeof ApiAgentsAgentIdFirewallRoute
  '/api/agents/$agentId/outcomes': typeof ApiAgentsAgentIdOutcomesRoute
  '/api/agents/$agentId/proofs': typeof ApiAgentsAgentIdProofsRoute
  '/api/agents/$agentId/reputation': typeof ApiAgentsAgentIdReputationRoute
  '/api/agents/owner/$address': typeof ApiAgentsOwnerAddressRoute
  '/api/firewalls/$firewallId/executions': typeof ApiFirewallsFirewallIdExecutionsRoute
  '/api/firewalls/$firewallId/functions': typeof ApiFirewallsFirewallIdFunctionsRoute
  '/api/firewalls/$firewallId/policy': typeof ApiFirewallsFirewallIdPolicyRoute
  '/api/firewalls/$firewallId/proofs': typeof ApiFirewallsFirewallIdProofsRoute
  '/api/firewalls/$firewallId/targets': typeof ApiFirewallsFirewallIdTargetsRoute
  '/api/outcomes/$executionId/anchor': typeof ApiOutcomesExecutionIdAnchorRoute
  '/api/outcomes/$executionId/evidence': typeof ApiOutcomesExecutionIdEvidenceRoute
  '/api/outcomes/$executionId/verify': typeof ApiOutcomesExecutionIdVerifyRoute
  '/api/proofs/$executionId/anchor': typeof ApiProofsExecutionIdAnchorRoute
  '/api/proofs/$executionId/verification': typeof ApiProofsExecutionIdVerificationRoute
  '/api/proofs/$executionId/verify': typeof ApiProofsExecutionIdVerifyRoute
  '/api/v1/agents/$agentId': typeof ApiV1AgentsAgentIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRoute
  '/api/v1/webhooks/$webhookId': typeof ApiV1WebhooksWebhookIdRoute
  '/api/agents/$agentId/': typeof ApiAgentsAgentIdIndexRoute
  '/api/firewalls/$firewallId/': typeof ApiFirewallsFirewallIdIndexRoute
  '/api/outcomes/$executionId/': typeof ApiOutcomesExecutionIdIndexRoute
  '/api/proofs/$executionId/': typeof ApiProofsExecutionIdIndexRoute
  '/api/v1/agents/': typeof ApiV1AgentsIndexRoute
  '/api/v1/firewalls/': typeof ApiV1FirewallsIndexRoute
  '/api/v1/webhooks/': typeof ApiV1WebhooksIndexRoute
  '/api/v1/firewalls/$firewallId/execute': typeof ApiV1FirewallsFirewallIdExecuteRoute
  '/api/v1/firewalls/$firewallId/functions': typeof ApiV1FirewallsFirewallIdFunctionsRoute
  '/api/v1/firewalls/$firewallId/targets': typeof ApiV1FirewallsFirewallIdTargetsRoute
  '/api/v1/outcomes/$executionId/verify': typeof ApiV1OutcomesExecutionIdVerifyRoute
  '/api/v1/proofs/$executionId/verify': typeof ApiV1ProofsExecutionIdVerifyRoute
  '/api/v1/firewalls/$firewallId/': typeof ApiV1FirewallsFirewallIdIndexRoute
  '/api/v1/outcomes/$executionId/': typeof ApiV1OutcomesExecutionIdIndexRoute
  '/api/v1/proofs/$executionId/': typeof ApiV1ProofsExecutionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/agents/new': typeof AgentsNewRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/api-keys': typeof DevelopersApiKeysRoute
  '/developers/docs': typeof DevelopersDocsRouteWithChildren
  '/developers/explorer': typeof DevelopersExplorerRoute
  '/developers/sandbox': typeof DevelopersSandboxRoute
  '/developers/sdk': typeof DevelopersSdkRoute
  '/developers/usage': typeof DevelopersUsageRoute
  '/developers/webhooks': typeof DevelopersWebhooksRoute
  '/firewalls/$firewallId': typeof FirewallsFirewallIdRoute
  '/firewalls/new': typeof FirewallsNewRoute
  '/outcomes/$executionId': typeof OutcomesExecutionIdRoute
  '/proofs/$proofId': typeof ProofsProofIdRoute
  '/agents': typeof AgentsIndexRoute
  '/developers': typeof DevelopersIndexRoute
  '/firewalls': typeof FirewallsIndexRoute
  '/proofs': typeof ProofsIndexRoute
  '/agents/$agentId/activity': typeof AgentsAgentIdActivityRoute
  '/agents/$agentId/firewall': typeof AgentsAgentIdFirewallRoute
  '/agents/$agentId/outcomes': typeof AgentsAgentIdOutcomesRoute
  '/agents/$agentId/proofs': typeof AgentsAgentIdProofsRoute
  '/agents/$agentId/reputation': typeof AgentsAgentIdReputationRoute
  '/api/agents/search': typeof ApiAgentsSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/developers/docs/demo': typeof DevelopersDocsDemoRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
  '/api/agents': typeof ApiAgentsIndexRoute
  '/api/firewalls': typeof ApiFirewallsIndexRoute
  '/api/proofs': typeof ApiProofsIndexRoute
  '/api/reputation': typeof ApiReputationIndexRoute
  '/api/agents/$agentId/activity': typeof ApiAgentsAgentIdActivityRoute
  '/api/agents/$agentId/events': typeof ApiAgentsAgentIdEventsRoute
  '/api/agents/$agentId/firewall': typeof ApiAgentsAgentIdFirewallRoute
  '/api/agents/$agentId/outcomes': typeof ApiAgentsAgentIdOutcomesRoute
  '/api/agents/$agentId/proofs': typeof ApiAgentsAgentIdProofsRoute
  '/api/agents/$agentId/reputation': typeof ApiAgentsAgentIdReputationRoute
  '/api/agents/owner/$address': typeof ApiAgentsOwnerAddressRoute
  '/api/firewalls/$firewallId/executions': typeof ApiFirewallsFirewallIdExecutionsRoute
  '/api/firewalls/$firewallId/functions': typeof ApiFirewallsFirewallIdFunctionsRoute
  '/api/firewalls/$firewallId/policy': typeof ApiFirewallsFirewallIdPolicyRoute
  '/api/firewalls/$firewallId/proofs': typeof ApiFirewallsFirewallIdProofsRoute
  '/api/firewalls/$firewallId/targets': typeof ApiFirewallsFirewallIdTargetsRoute
  '/api/outcomes/$executionId/anchor': typeof ApiOutcomesExecutionIdAnchorRoute
  '/api/outcomes/$executionId/evidence': typeof ApiOutcomesExecutionIdEvidenceRoute
  '/api/outcomes/$executionId/verify': typeof ApiOutcomesExecutionIdVerifyRoute
  '/api/proofs/$executionId/anchor': typeof ApiProofsExecutionIdAnchorRoute
  '/api/proofs/$executionId/verification': typeof ApiProofsExecutionIdVerificationRoute
  '/api/proofs/$executionId/verify': typeof ApiProofsExecutionIdVerifyRoute
  '/api/v1/agents/$agentId': typeof ApiV1AgentsAgentIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRoute
  '/api/v1/webhooks/$webhookId': typeof ApiV1WebhooksWebhookIdRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdIndexRoute
  '/api/firewalls/$firewallId': typeof ApiFirewallsFirewallIdIndexRoute
  '/api/outcomes/$executionId': typeof ApiOutcomesExecutionIdIndexRoute
  '/api/proofs/$executionId': typeof ApiProofsExecutionIdIndexRoute
  '/api/v1/agents': typeof ApiV1AgentsIndexRoute
  '/api/v1/firewalls': typeof ApiV1FirewallsIndexRoute
  '/api/v1/webhooks': typeof ApiV1WebhooksIndexRoute
  '/api/v1/firewalls/$firewallId/execute': typeof ApiV1FirewallsFirewallIdExecuteRoute
  '/api/v1/firewalls/$firewallId/functions': typeof ApiV1FirewallsFirewallIdFunctionsRoute
  '/api/v1/firewalls/$firewallId/targets': typeof ApiV1FirewallsFirewallIdTargetsRoute
  '/api/v1/outcomes/$executionId/verify': typeof ApiV1OutcomesExecutionIdVerifyRoute
  '/api/v1/proofs/$executionId/verify': typeof ApiV1ProofsExecutionIdVerifyRoute
  '/api/v1/firewalls/$firewallId': typeof ApiV1FirewallsFirewallIdIndexRoute
  '/api/v1/outcomes/$executionId': typeof ApiV1OutcomesExecutionIdIndexRoute
  '/api/v1/proofs/$executionId': typeof ApiV1ProofsExecutionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/agents/new': typeof AgentsNewRoute
  '/developers/api': typeof DevelopersApiRoute
  '/developers/api-keys': typeof DevelopersApiKeysRoute
  '/developers/docs': typeof DevelopersDocsRouteWithChildren
  '/developers/explorer': typeof DevelopersExplorerRoute
  '/developers/sandbox': typeof DevelopersSandboxRoute
  '/developers/sdk': typeof DevelopersSdkRoute
  '/developers/usage': typeof DevelopersUsageRoute
  '/developers/webhooks': typeof DevelopersWebhooksRoute
  '/firewalls/$firewallId': typeof FirewallsFirewallIdRoute
  '/firewalls/new': typeof FirewallsNewRoute
  '/outcomes/$executionId': typeof OutcomesExecutionIdRoute
  '/proofs/$proofId': typeof ProofsProofIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/firewalls/': typeof FirewallsIndexRoute
  '/proofs/': typeof ProofsIndexRoute
  '/agents/$agentId/activity': typeof AgentsAgentIdActivityRoute
  '/agents/$agentId/firewall': typeof AgentsAgentIdFirewallRoute
  '/agents/$agentId/outcomes': typeof AgentsAgentIdOutcomesRoute
  '/agents/$agentId/proofs': typeof AgentsAgentIdProofsRoute
  '/agents/$agentId/reputation': typeof AgentsAgentIdReputationRoute
  '/api/agents/search': typeof ApiAgentsSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/developers/docs/demo': typeof DevelopersDocsDemoRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
  '/api/agents/': typeof ApiAgentsIndexRoute
  '/api/firewalls/': typeof ApiFirewallsIndexRoute
  '/api/proofs/': typeof ApiProofsIndexRoute
  '/api/reputation/': typeof ApiReputationIndexRoute
  '/api/agents/$agentId/activity': typeof ApiAgentsAgentIdActivityRoute
  '/api/agents/$agentId/events': typeof ApiAgentsAgentIdEventsRoute
  '/api/agents/$agentId/firewall': typeof ApiAgentsAgentIdFirewallRoute
  '/api/agents/$agentId/outcomes': typeof ApiAgentsAgentIdOutcomesRoute
  '/api/agents/$agentId/proofs': typeof ApiAgentsAgentIdProofsRoute
  '/api/agents/$agentId/reputation': typeof ApiAgentsAgentIdReputationRoute
  '/api/agents/owner/$address': typeof ApiAgentsOwnerAddressRoute
  '/api/firewalls/$firewallId/executions': typeof ApiFirewallsFirewallIdExecutionsRoute
  '/api/firewalls/$firewallId/functions': typeof ApiFirewallsFirewallIdFunctionsRoute
  '/api/firewalls/$firewallId/policy': typeof ApiFirewallsFirewallIdPolicyRoute
  '/api/firewalls/$firewallId/proofs': typeof ApiFirewallsFirewallIdProofsRoute
  '/api/firewalls/$firewallId/targets': typeof ApiFirewallsFirewallIdTargetsRoute
  '/api/outcomes/$executionId/anchor': typeof ApiOutcomesExecutionIdAnchorRoute
  '/api/outcomes/$executionId/evidence': typeof ApiOutcomesExecutionIdEvidenceRoute
  '/api/outcomes/$executionId/verify': typeof ApiOutcomesExecutionIdVerifyRoute
  '/api/proofs/$executionId/anchor': typeof ApiProofsExecutionIdAnchorRoute
  '/api/proofs/$executionId/verification': typeof ApiProofsExecutionIdVerificationRoute
  '/api/proofs/$executionId/verify': typeof ApiProofsExecutionIdVerifyRoute
  '/api/v1/agents/$agentId': typeof ApiV1AgentsAgentIdRoute
  '/api/v1/executions/$executionId': typeof ApiV1ExecutionsExecutionIdRoute
  '/api/v1/webhooks/$webhookId': typeof ApiV1WebhooksWebhookIdRoute
  '/api/agents/$agentId/': typeof ApiAgentsAgentIdIndexRoute
  '/api/firewalls/$firewallId/': typeof ApiFirewallsFirewallIdIndexRoute
  '/api/outcomes/$executionId/': typeof ApiOutcomesExecutionIdIndexRoute
  '/api/proofs/$executionId/': typeof ApiProofsExecutionIdIndexRoute
  '/api/v1/agents/': typeof ApiV1AgentsIndexRoute
  '/api/v1/firewalls/': typeof ApiV1FirewallsIndexRoute
  '/api/v1/webhooks/': typeof ApiV1WebhooksIndexRoute
  '/api/v1/firewalls/$firewallId/execute': typeof ApiV1FirewallsFirewallIdExecuteRoute
  '/api/v1/firewalls/$firewallId/functions': typeof ApiV1FirewallsFirewallIdFunctionsRoute
  '/api/v1/firewalls/$firewallId/targets': typeof ApiV1FirewallsFirewallIdTargetsRoute
  '/api/v1/outcomes/$executionId/verify': typeof ApiV1OutcomesExecutionIdVerifyRoute
  '/api/v1/proofs/$executionId/verify': typeof ApiV1ProofsExecutionIdVerifyRoute
  '/api/v1/firewalls/$firewallId/': typeof ApiV1FirewallsFirewallIdIndexRoute
  '/api/v1/outcomes/$executionId/': typeof ApiV1OutcomesExecutionIdIndexRoute
  '/api/v1/proofs/$executionId/': typeof ApiV1ProofsExecutionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/directory'
    | '/login'
    | '/settings'
    | '/agents/new'
    | '/developers/api'
    | '/developers/api-keys'
    | '/developers/docs'
    | '/developers/explorer'
    | '/developers/sandbox'
    | '/developers/sdk'
    | '/developers/usage'
    | '/developers/webhooks'
    | '/firewalls/$firewallId'
    | '/firewalls/new'
    | '/outcomes/$executionId'
    | '/proofs/$proofId'
    | '/agents/'
    | '/developers/'
    | '/firewalls/'
    | '/proofs/'
    | '/agents/$agentId/activity'
    | '/agents/$agentId/firewall'
    | '/agents/$agentId/outcomes'
    | '/agents/$agentId/proofs'
    | '/agents/$agentId/reputation'
    | '/api/agents/search'
    | '/api/auth/$'
    | '/developers/docs/demo'
    | '/agents/$agentId/'
    | '/api/agents/'
    | '/api/firewalls/'
    | '/api/proofs/'
    | '/api/reputation/'
    | '/api/agents/$agentId/activity'
    | '/api/agents/$agentId/events'
    | '/api/agents/$agentId/firewall'
    | '/api/agents/$agentId/outcomes'
    | '/api/agents/$agentId/proofs'
    | '/api/agents/$agentId/reputation'
    | '/api/agents/owner/$address'
    | '/api/firewalls/$firewallId/executions'
    | '/api/firewalls/$firewallId/functions'
    | '/api/firewalls/$firewallId/policy'
    | '/api/firewalls/$firewallId/proofs'
    | '/api/firewalls/$firewallId/targets'
    | '/api/outcomes/$executionId/anchor'
    | '/api/outcomes/$executionId/evidence'
    | '/api/outcomes/$executionId/verify'
    | '/api/proofs/$executionId/anchor'
    | '/api/proofs/$executionId/verification'
    | '/api/proofs/$executionId/verify'
    | '/api/v1/agents/$agentId'
    | '/api/v1/executions/$executionId'
    | '/api/v1/webhooks/$webhookId'
    | '/api/agents/$agentId/'
    | '/api/firewalls/$firewallId/'
    | '/api/outcomes/$executionId/'
    | '/api/proofs/$executionId/'
    | '/api/v1/agents/'
    | '/api/v1/firewalls/'
    | '/api/v1/webhooks/'
    | '/api/v1/firewalls/$firewallId/execute'
    | '/api/v1/firewalls/$firewallId/functions'
    | '/api/v1/firewalls/$firewallId/targets'
    | '/api/v1/outcomes/$executionId/verify'
    | '/api/v1/proofs/$executionId/verify'
    | '/api/v1/firewalls/$firewallId/'
    | '/api/v1/outcomes/$executionId/'
    | '/api/v1/proofs/$executionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/directory'
    | '/login'
    | '/settings'
    | '/agents/new'
    | '/developers/api'
    | '/developers/api-keys'
    | '/developers/docs'
    | '/developers/explorer'
    | '/developers/sandbox'
    | '/developers/sdk'
    | '/developers/usage'
    | '/developers/webhooks'
    | '/firewalls/$firewallId'
    | '/firewalls/new'
    | '/outcomes/$executionId'
    | '/proofs/$proofId'
    | '/agents'
    | '/developers'
    | '/firewalls'
    | '/proofs'
    | '/agents/$agentId/activity'
    | '/agents/$agentId/firewall'
    | '/agents/$agentId/outcomes'
    | '/agents/$agentId/proofs'
    | '/agents/$agentId/reputation'
    | '/api/agents/search'
    | '/api/auth/$'
    | '/developers/docs/demo'
    | '/agents/$agentId'
    | '/api/agents'
    | '/api/firewalls'
    | '/api/proofs'
    | '/api/reputation'
    | '/api/agents/$agentId/activity'
    | '/api/agents/$agentId/events'
    | '/api/agents/$agentId/firewall'
    | '/api/agents/$agentId/outcomes'
    | '/api/agents/$agentId/proofs'
    | '/api/agents/$agentId/reputation'
    | '/api/agents/owner/$address'
    | '/api/firewalls/$firewallId/executions'
    | '/api/firewalls/$firewallId/functions'
    | '/api/firewalls/$firewallId/policy'
    | '/api/firewalls/$firewallId/proofs'
    | '/api/firewalls/$firewallId/targets'
    | '/api/outcomes/$executionId/anchor'
    | '/api/outcomes/$executionId/evidence'
    | '/api/outcomes/$executionId/verify'
    | '/api/proofs/$executionId/anchor'
    | '/api/proofs/$executionId/verification'
    | '/api/proofs/$executionId/verify'
    | '/api/v1/agents/$agentId'
    | '/api/v1/executions/$executionId'
    | '/api/v1/webhooks/$webhookId'
    | '/api/agents/$agentId'
    | '/api/firewalls/$firewallId'
    | '/api/outcomes/$executionId'
    | '/api/proofs/$executionId'
    | '/api/v1/agents'
    | '/api/v1/firewalls'
    | '/api/v1/webhooks'
    | '/api/v1/firewalls/$firewallId/execute'
    | '/api/v1/firewalls/$firewallId/functions'
    | '/api/v1/firewalls/$firewallId/targets'
    | '/api/v1/outcomes/$executionId/verify'
    | '/api/v1/proofs/$executionId/verify'
    | '/api/v1/firewalls/$firewallId'
    | '/api/v1/outcomes/$executionId'
    | '/api/v1/proofs/$executionId'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/directory'
    | '/login'
    | '/settings'
    | '/agents/new'
    | '/developers/api'
    | '/developers/api-keys'
    | '/developers/docs'
    | '/developers/explorer'
    | '/developers/sandbox'
    | '/developers/sdk'
    | '/developers/usage'
    | '/developers/webhooks'
    | '/firewalls/$firewallId'
    | '/firewalls/new'
    | '/outcomes/$executionId'
    | '/proofs/$proofId'
    | '/agents/'
    | '/developers/'
    | '/firewalls/'
    | '/proofs/'
    | '/agents/$agentId/activity'
    | '/agents/$agentId/firewall'
    | '/agents/$agentId/outcomes'
    | '/agents/$agentId/proofs'
    | '/agents/$agentId/reputation'
    | '/api/agents/search'
    | '/api/auth/$'
    | '/developers/docs/demo'
    | '/agents/$agentId/'
    | '/api/agents/'
    | '/api/firewalls/'
    | '/api/proofs/'
    | '/api/reputation/'
    | '/api/agents/$agentId/activity'
    | '/api/agents/$agentId/events'
    | '/api/agents/$agentId/firewall'
    | '/api/agents/$agentId/outcomes'
    | '/api/agents/$agentId/proofs'
    | '/api/agents/$agentId/reputation'
    | '/api/agents/owner/$address'
    | '/api/firewalls/$firewallId/executions'
    | '/api/firewalls/$firewallId/functions'
    | '/api/firewalls/$firewallId/policy'
    | '/api/firewalls/$firewallId/proofs'
    | '/api/firewalls/$firewallId/targets'
    | '/api/outcomes/$executionId/anchor'
    | '/api/outcomes/$executionId/evidence'
    | '/api/outcomes/$executionId/verify'
    | '/api/proofs/$executionId/anchor'
    | '/api/proofs/$executionId/verification'
    | '/api/proofs/$executionId/verify'
    | '/api/v1/agents/$agentId'
    | '/api/v1/executions/$executionId'
    | '/api/v1/webhooks/$webhookId'
    | '/api/agents/$agentId/'
    | '/api/firewalls/$firewallId/'
    | '/api/outcomes/$executionId/'
    | '/api/proofs/$executionId/'
    | '/api/v1/agents/'
    | '/api/v1/firewalls/'
    | '/api/v1/webhooks/'
    | '/api/v1/firewalls/$firewallId/execute'
    | '/api/v1/firewalls/$firewallId/functions'
    | '/api/v1/firewalls/$firewallId/targets'
    | '/api/v1/outcomes/$executionId/verify'
    | '/api/v1/proofs/$executionId/verify'
    | '/api/v1/firewalls/$firewallId/'
    | '/api/v1/outcomes/$executionId/'
    | '/api/v1/proofs/$executionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DirectoryRoute: typeof DirectoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AgentsNewRoute: typeof AgentsNewRoute
  DevelopersApiRoute: typeof DevelopersApiRoute
  DevelopersApiKeysRoute: typeof DevelopersApiKeysRoute
  DevelopersDocsRoute: typeof DevelopersDocsRouteWithChildren
  DevelopersExplorerRoute: typeof DevelopersExplorerRoute
  DevelopersSandboxRoute: typeof DevelopersSandboxRoute
  DevelopersSdkRoute: typeof DevelopersSdkRoute
  DevelopersUsageRoute: typeof DevelopersUsageRoute
  DevelopersWebhooksRoute: typeof DevelopersWebhooksRoute
  FirewallsFirewallIdRoute: typeof FirewallsFirewallIdRoute
  FirewallsNewRoute: typeof FirewallsNewRoute
  OutcomesExecutionIdRoute: typeof OutcomesExecutionIdRoute
  ProofsProofIdRoute: typeof ProofsProofIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
  FirewallsIndexRoute: typeof FirewallsIndexRoute
  ProofsIndexRoute: typeof ProofsIndexRoute
  AgentsAgentIdActivityRoute: typeof AgentsAgentIdActivityRoute
  AgentsAgentIdFirewallRoute: typeof AgentsAgentIdFirewallRoute
  AgentsAgentIdOutcomesRoute: typeof AgentsAgentIdOutcomesRoute
  AgentsAgentIdProofsRoute: typeof AgentsAgentIdProofsRoute
  AgentsAgentIdReputationRoute: typeof AgentsAgentIdReputationRoute
  ApiAgentsSearchRoute: typeof ApiAgentsSearchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
  ApiAgentsIndexRoute: typeof ApiAgentsIndexRoute
  ApiFirewallsIndexRoute: typeof ApiFirewallsIndexRoute
  ApiProofsIndexRoute: typeof ApiProofsIndexRoute
  ApiReputationIndexRoute: typeof ApiReputationIndexRoute
  ApiAgentsAgentIdActivityRoute: typeof ApiAgentsAgentIdActivityRoute
  ApiAgentsAgentIdEventsRoute: typeof ApiAgentsAgentIdEventsRoute
  ApiAgentsAgentIdFirewallRoute: typeof ApiAgentsAgentIdFirewallRoute
  ApiAgentsAgentIdOutcomesRoute: typeof ApiAgentsAgentIdOutcomesRoute
  ApiAgentsAgentIdProofsRoute: typeof ApiAgentsAgentIdProofsRoute
  ApiAgentsAgentIdReputationRoute: typeof ApiAgentsAgentIdReputationRoute
  ApiAgentsOwnerAddressRoute: typeof ApiAgentsOwnerAddressRoute
  ApiFirewallsFirewallIdExecutionsRoute: typeof ApiFirewallsFirewallIdExecutionsRoute
  ApiFirewallsFirewallIdFunctionsRoute: typeof ApiFirewallsFirewallIdFunctionsRoute
  ApiFirewallsFirewallIdPolicyRoute: typeof ApiFirewallsFirewallIdPolicyRoute
  ApiFirewallsFirewallIdProofsRoute: typeof ApiFirewallsFirewallIdProofsRoute
  ApiFirewallsFirewallIdTargetsRoute: typeof ApiFirewallsFirewallIdTargetsRoute
  ApiOutcomesExecutionIdAnchorRoute: typeof ApiOutcomesExecutionIdAnchorRoute
  ApiOutcomesExecutionIdEvidenceRoute: typeof ApiOutcomesExecutionIdEvidenceRoute
  ApiOutcomesExecutionIdVerifyRoute: typeof ApiOutcomesExecutionIdVerifyRoute
  ApiProofsExecutionIdAnchorRoute: typeof ApiProofsExecutionIdAnchorRoute
  ApiProofsExecutionIdVerificationRoute: typeof ApiProofsExecutionIdVerificationRoute
  ApiProofsExecutionIdVerifyRoute: typeof ApiProofsExecutionIdVerifyRoute
  ApiV1AgentsAgentIdRoute: typeof ApiV1AgentsAgentIdRoute
  ApiV1ExecutionsExecutionIdRoute: typeof ApiV1ExecutionsExecutionIdRoute
  ApiV1WebhooksWebhookIdRoute: typeof ApiV1WebhooksWebhookIdRoute
  ApiAgentsAgentIdIndexRoute: typeof ApiAgentsAgentIdIndexRoute
  ApiFirewallsFirewallIdIndexRoute: typeof ApiFirewallsFirewallIdIndexRoute
  ApiOutcomesExecutionIdIndexRoute: typeof ApiOutcomesExecutionIdIndexRoute
  ApiProofsExecutionIdIndexRoute: typeof ApiProofsExecutionIdIndexRoute
  ApiV1AgentsIndexRoute: typeof ApiV1AgentsIndexRoute
  ApiV1FirewallsIndexRoute: typeof ApiV1FirewallsIndexRoute
  ApiV1WebhooksIndexRoute: typeof ApiV1WebhooksIndexRoute
  ApiV1FirewallsFirewallIdExecuteRoute: typeof ApiV1FirewallsFirewallIdExecuteRoute
  ApiV1FirewallsFirewallIdFunctionsRoute: typeof ApiV1FirewallsFirewallIdFunctionsRoute
  ApiV1FirewallsFirewallIdTargetsRoute: typeof ApiV1FirewallsFirewallIdTargetsRoute
  ApiV1OutcomesExecutionIdVerifyRoute: typeof ApiV1OutcomesExecutionIdVerifyRoute
  ApiV1ProofsExecutionIdVerifyRoute: typeof ApiV1ProofsExecutionIdVerifyRoute
  ApiV1FirewallsFirewallIdIndexRoute: typeof ApiV1FirewallsFirewallIdIndexRoute
  ApiV1OutcomesExecutionIdIndexRoute: typeof ApiV1OutcomesExecutionIdIndexRoute
  ApiV1ProofsExecutionIdIndexRoute: typeof ApiV1ProofsExecutionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/': {
      id: '/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/api': {
      id: '/developers/api'
      path: '/developers/api'
      fullPath: '/developers/api'
      preLoaderRoute: typeof DevelopersApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/api-keys': {
      id: '/developers/api-keys'
      path: '/developers/api-keys'
      fullPath: '/developers/api-keys'
      preLoaderRoute: typeof DevelopersApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/docs': {
      id: '/developers/docs'
      path: '/developers/docs'
      fullPath: '/developers/docs'
      preLoaderRoute: typeof DevelopersDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/explorer': {
      id: '/developers/explorer'
      path: '/developers/explorer'
      fullPath: '/developers/explorer'
      preLoaderRoute: typeof DevelopersExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/sandbox': {
      id: '/developers/sandbox'
      path: '/developers/sandbox'
      fullPath: '/developers/sandbox'
      preLoaderRoute: typeof DevelopersSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/sdk': {
      id: '/developers/sdk'
      path: '/developers/sdk'
      fullPath: '/developers/sdk'
      preLoaderRoute: typeof DevelopersSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/usage': {
      id: '/developers/usage'
      path: '/developers/usage'
      fullPath: '/developers/usage'
      preLoaderRoute: typeof DevelopersUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/webhooks': {
      id: '/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/developers/webhooks'
      preLoaderRoute: typeof DevelopersWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewalls/': {
      id: '/firewalls/'
      path: '/firewalls'
      fullPath: '/firewalls/'
      preLoaderRoute: typeof FirewallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewalls/$firewallId': {
      id: '/firewalls/$firewallId'
      path: '/firewalls/$firewallId'
      fullPath: '/firewalls/$firewallId'
      preLoaderRoute: typeof FirewallsFirewallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewalls/new': {
      id: '/firewalls/new'
      path: '/firewalls/new'
      fullPath: '/firewalls/new'
      preLoaderRoute: typeof FirewallsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/$executionId': {
      id: '/outcomes/$executionId'
      path: '/outcomes/$executionId'
      fullPath: '/outcomes/$executionId'
      preLoaderRoute: typeof OutcomesExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proofs/': {
      id: '/proofs/'
      path: '/proofs'
      fullPath: '/proofs/'
      preLoaderRoute: typeof ProofsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proofs/$proofId': {
      id: '/proofs/$proofId'
      path: '/proofs/$proofId'
      fullPath: '/proofs/$proofId'
      preLoaderRoute: typeof ProofsProofIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/activity': {
      id: '/agents/$agentId/activity'
      path: '/agents/$agentId/activity'
      fullPath: '/agents/$agentId/activity'
      preLoaderRoute: typeof AgentsAgentIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/firewall': {
      id: '/agents/$agentId/firewall'
      path: '/agents/$agentId/firewall'
      fullPath: '/agents/$agentId/firewall'
      preLoaderRoute: typeof AgentsAgentIdFirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/outcomes': {
      id: '/agents/$agentId/outcomes'
      path: '/agents/$agentId/outcomes'
      fullPath: '/agents/$agentId/outcomes'
      preLoaderRoute: typeof AgentsAgentIdOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/proofs': {
      id: '/agents/$agentId/proofs'
      path: '/agents/$agentId/proofs'
      fullPath: '/agents/$agentId/proofs'
      preLoaderRoute: typeof AgentsAgentIdProofsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/reputation': {
      id: '/agents/$agentId/reputation'
      path: '/agents/$agentId/reputation'
      fullPath: '/agents/$agentId/reputation'
      preLoaderRoute: typeof AgentsAgentIdReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/': {
      id: '/api/agents/'
      path: '/api/agents'
      fullPath: '/api/agents/'
      preLoaderRoute: typeof ApiAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/search': {
      id: '/api/agents/search'
      path: '/api/agents/search'
      fullPath: '/api/agents/search'
      preLoaderRoute: typeof ApiAgentsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firewalls/': {
      id: '/api/firewalls/'
      path: '/api/firewalls'
      fullPath: '/api/firewalls/'
      preLoaderRoute: typeof ApiFirewallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proofs/': {
      id: '/api/proofs/'
      path: '/api/proofs'
      fullPath: '/api/proofs/'
      preLoaderRoute: typeof ApiProofsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reputation/': {
      id: '/api/reputation/'
      path: '/api/reputation'
      fullPath: '/api/reputation/'
      preLoaderRoute: typeof ApiReputationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/docs/demo': {
      id: '/developers/docs/demo'
      path: '/demo'
      fullPath: '/developers/docs/demo'
      preLoaderRoute: typeof DevelopersDocsDemoRouteImport
      parentRoute: typeof DevelopersDocsRoute
    }
    '/api/agents/$agentId/': {
      id: '/api/agents/$agentId/'
      path: '/api/agents/$agentId'
      fullPath: '/api/agents/$agentId/'
      preLoaderRoute: typeof ApiAgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId/activity': {
      id: '/api/agents/$agentId/activity'
      path: '/api/agents/$agentId/activity'
      fullPath: '/api/agents/$agentId/activity'
      preLoaderRoute: typeof ApiAgentsAgentIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId/events': {
      id: '/api/agents/$agentId/events'
      path: '/api/agents/$agentId/events'
      fullPath: '/api/agents/$agentId/events'
      preLoaderRoute: typeof ApiAgentsAgentIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId/firewall': {
      id: '/api/agents/$agentId/firewall'
      path: '/api/agents/$agentId/firewall'
      fullPath: '/api/agents/$agentId/firewall'
      preLoaderRoute: typeof ApiAgentsAgentIdFirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId/outcomes': {
      id: '/api/agents/$agentId/outcomes'
      path: '/api/agents/$agentId/outcomes'
      fullPath: '/api/agents/$agentId/outcomes'
      preLoaderRoute: typeof ApiAgentsAgentIdOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId/proofs': {
      id: '/api/agents/$agentId/proofs'
      path: '/api/agents/$agentId/proofs'
      fullPath: '/api/agents/$agentId/proofs'
      preLoaderRoute: typeof ApiAgentsAgentIdProofsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId/reputation': {
      id: '/api/agents/$agentId/reputation'
      path: '/api/agents/$agentId/reputation'
      fullPath: '/api/agents/$agentId/reputation'
      preLoaderRoute: typeof ApiAgentsAgentIdReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/owner/$address': {
      id: '/api/agents/owner/$address'
      path: '/api/agents/owner/$address'
      fullPath: '/api/agents/owner/$address'
      preLoaderRoute: typeof ApiAgentsOwnerAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firewalls/$firewallId/': {
      id: '/api/firewalls/$firewallId/'
      path: '/api/firewalls/$firewallId'
      fullPath: '/api/firewalls/$firewallId/'
      preLoaderRoute: typeof ApiFirewallsFirewallIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firewalls/$firewallId/executions': {
      id: '/api/firewalls/$firewallId/executions'
      path: '/api/firewalls/$firewallId/executions'
      fullPath: '/api/firewalls/$firewallId/executions'
      preLoaderRoute: typeof ApiFirewallsFirewallIdExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firewalls/$firewallId/functions': {
      id: '/api/firewalls/$firewallId/functions'
      path: '/api/firewalls/$firewallId/functions'
      fullPath: '/api/firewalls/$firewallId/functions'
      preLoaderRoute: typeof ApiFirewallsFirewallIdFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firewalls/$firewallId/policy': {
      id: '/api/firewalls/$firewallId/policy'
      path: '/api/firewalls/$firewallId/policy'
      fullPath: '/api/firewalls/$firewallId/policy'
      preLoaderRoute: typeof ApiFirewallsFirewallIdPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firewalls/$firewallId/proofs': {
      id: '/api/firewalls/$firewallId/proofs'
      path: '/api/firewalls/$firewallId/proofs'
      fullPath: '/api/firewalls/$firewallId/proofs'
      preLoaderRoute: typeof ApiFirewallsFirewallIdProofsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firewalls/$firewallId/targets': {
      id: '/api/firewalls/$firewallId/targets'
      path: '/api/firewalls/$firewallId/targets'
      fullPath: '/api/firewalls/$firewallId/targets'
      preLoaderRoute: typeof ApiFirewallsFirewallIdTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outcomes/$executionId/': {
      id: '/api/outcomes/$executionId/'
      path: '/api/outcomes/$executionId'
      fullPath: '/api/outcomes/$executionId/'
      preLoaderRoute: typeof ApiOutcomesExecutionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outcomes/$executionId/anchor': {
      id: '/api/outcomes/$executionId/anchor'
      path: '/api/outcomes/$executionId/anchor'
      fullPath: '/api/outcomes/$executionId/anchor'
      preLoaderRoute: typeof ApiOutcomesExecutionIdAnchorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outcomes/$executionId/evidence': {
      id: '/api/outcomes/$executionId/evidence'
      path: '/api/outcomes/$executionId/evidence'
      fullPath: '/api/outcomes/$executionId/evidence'
      preLoaderRoute: typeof ApiOutcomesExecutionIdEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outcomes/$executionId/verify': {
      id: '/api/outcomes/$executionId/verify'
      path: '/api/outcomes/$executionId/verify'
      fullPath: '/api/outcomes/$executionId/verify'
      preLoaderRoute: typeof ApiOutcomesExecutionIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proofs/$executionId/': {
      id: '/api/proofs/$executionId/'
      path: '/api/proofs/$executionId'
      fullPath: '/api/proofs/$executionId/'
      preLoaderRoute: typeof ApiProofsExecutionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proofs/$executionId/anchor': {
      id: '/api/proofs/$executionId/anchor'
      path: '/api/proofs/$executionId/anchor'
      fullPath: '/api/proofs/$executionId/anchor'
      preLoaderRoute: typeof ApiProofsExecutionIdAnchorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proofs/$executionId/verification': {
      id: '/api/proofs/$executionId/verification'
      path: '/api/proofs/$executionId/verification'
      fullPath: '/api/proofs/$executionId/verification'
      preLoaderRoute: typeof ApiProofsExecutionIdVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proofs/$executionId/verify': {
      id: '/api/proofs/$executionId/verify'
      path: '/api/proofs/$executionId/verify'
      fullPath: '/api/proofs/$executionId/verify'
      preLoaderRoute: typeof ApiProofsExecutionIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/agents/': {
      id: '/api/v1/agents/'
      path: '/api/v1/agents'
      fullPath: '/api/v1/agents/'
      preLoaderRoute: typeof ApiV1AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/agents/$agentId': {
      id: '/api/v1/agents/$agentId'
      path: '/api/v1/agents/$agentId'
      fullPath: '/api/v1/agents/$agentId'
      preLoaderRoute: typeof ApiV1AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/executions/$executionId': {
      id: '/api/v1/executions/$executionId'
      path: '/api/v1/executions/$executionId'
      fullPath: '/api/v1/executions/$executionId'
      preLoaderRoute: typeof ApiV1ExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/firewalls/': {
      id: '/api/v1/firewalls/'
      path: '/api/v1/firewalls'
      fullPath: '/api/v1/firewalls/'
      preLoaderRoute: typeof ApiV1FirewallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/webhooks/': {
      id: '/api/v1/webhooks/'
      path: '/api/v1/webhooks'
      fullPath: '/api/v1/webhooks/'
      preLoaderRoute: typeof ApiV1WebhooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/webhooks/$webhookId': {
      id: '/api/v1/webhooks/$webhookId'
      path: '/api/v1/webhooks/$webhookId'
      fullPath: '/api/v1/webhooks/$webhookId'
      preLoaderRoute: typeof ApiV1WebhooksWebhookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/firewalls/$firewallId/': {
      id: '/api/v1/firewalls/$firewallId/'
      path: '/api/v1/firewalls/$firewallId'
      fullPath: '/api/v1/firewalls/$firewallId/'
      preLoaderRoute: typeof ApiV1FirewallsFirewallIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/firewalls/$firewallId/execute': {
      id: '/api/v1/firewalls/$firewallId/execute'
      path: '/api/v1/firewalls/$firewallId/execute'
      fullPath: '/api/v1/firewalls/$firewallId/execute'
      preLoaderRoute: typeof ApiV1FirewallsFirewallIdExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/firewalls/$firewallId/functions': {
      id: '/api/v1/firewalls/$firewallId/functions'
      path: '/api/v1/firewalls/$firewallId/functions'
      fullPath: '/api/v1/firewalls/$firewallId/functions'
      preLoaderRoute: typeof ApiV1FirewallsFirewallIdFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/firewalls/$firewallId/targets': {
      id: '/api/v1/firewalls/$firewallId/targets'
      path: '/api/v1/firewalls/$firewallId/targets'
      fullPath: '/api/v1/firewalls/$firewallId/targets'
      preLoaderRoute: typeof ApiV1FirewallsFirewallIdTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/outcomes/$executionId/': {
      id: '/api/v1/outcomes/$executionId/'
      path: '/api/v1/outcomes/$executionId'
      fullPath: '/api/v1/outcomes/$executionId/'
      preLoaderRoute: typeof ApiV1OutcomesExecutionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/outcomes/$executionId/verify': {
      id: '/api/v1/outcomes/$executionId/verify'
      path: '/api/v1/outcomes/$executionId/verify'
      fullPath: '/api/v1/outcomes/$executionId/verify'
      preLoaderRoute: typeof ApiV1OutcomesExecutionIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/proofs/$executionId/': {
      id: '/api/v1/proofs/$executionId/'
      path: '/api/v1/proofs/$executionId'
      fullPath: '/api/v1/proofs/$executionId/'
      preLoaderRoute: typeof ApiV1ProofsExecutionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/proofs/$executionId/verify': {
      id: '/api/v1/proofs/$executionId/verify'
      path: '/api/v1/proofs/$executionId/verify'
      fullPath: '/api/v1/proofs/$executionId/verify'
      preLoaderRoute: typeof ApiV1ProofsExecutionIdVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DevelopersDocsRouteChildren {
  DevelopersDocsDemoRoute: typeof DevelopersDocsDemoRoute
}

const DevelopersDocsRouteChildren: DevelopersDocsRouteChildren = {
  DevelopersDocsDemoRoute: DevelopersDocsDemoRoute,
}

const DevelopersDocsRouteWithChildren = DevelopersDocsRoute._addFileChildren(
  DevelopersDocsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DirectoryRoute: DirectoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AgentsNewRoute: AgentsNewRoute,
  DevelopersApiRoute: DevelopersApiRoute,
  DevelopersApiKeysRoute: DevelopersApiKeysRoute,
  DevelopersDocsRoute: DevelopersDocsRouteWithChildren,
  DevelopersExplorerRoute: DevelopersExplorerRoute,
  DevelopersSandboxRoute: DevelopersSandboxRoute,
  DevelopersSdkRoute: DevelopersSdkRoute,
  DevelopersUsageRoute: DevelopersUsageRoute,
  DevelopersWebhooksRoute: DevelopersWebhooksRoute,
  FirewallsFirewallIdRoute: FirewallsFirewallIdRoute,
  FirewallsNewRoute: FirewallsNewRoute,
  OutcomesExecutionIdRoute: OutcomesExecutionIdRoute,
  ProofsProofIdRoute: ProofsProofIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
  FirewallsIndexRoute: FirewallsIndexRoute,
  ProofsIndexRoute: ProofsIndexRoute,
  AgentsAgentIdActivityRoute: AgentsAgentIdActivityRoute,
  AgentsAgentIdFirewallRoute: AgentsAgentIdFirewallRoute,
  AgentsAgentIdOutcomesRoute: AgentsAgentIdOutcomesRoute,
  AgentsAgentIdProofsRoute: AgentsAgentIdProofsRoute,
  AgentsAgentIdReputationRoute: AgentsAgentIdReputationRoute,
  ApiAgentsSearchRoute: ApiAgentsSearchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
  ApiAgentsIndexRoute: ApiAgentsIndexRoute,
  ApiFirewallsIndexRoute: ApiFirewallsIndexRoute,
  ApiProofsIndexRoute: ApiProofsIndexRoute,
  ApiReputationIndexRoute: ApiReputationIndexRoute,
  ApiAgentsAgentIdActivityRoute: ApiAgentsAgentIdActivityRoute,
  ApiAgentsAgentIdEventsRoute: ApiAgentsAgentIdEventsRoute,
  ApiAgentsAgentIdFirewallRoute: ApiAgentsAgentIdFirewallRoute,
  ApiAgentsAgentIdOutcomesRoute: ApiAgentsAgentIdOutcomesRoute,
  ApiAgentsAgentIdProofsRoute: ApiAgentsAgentIdProofsRoute,
  ApiAgentsAgentIdReputationRoute: ApiAgentsAgentIdReputationRoute,
  ApiAgentsOwnerAddressRoute: ApiAgentsOwnerAddressRoute,
  ApiFirewallsFirewallIdExecutionsRoute: ApiFirewallsFirewallIdExecutionsRoute,
  ApiFirewallsFirewallIdFunctionsRoute: ApiFirewallsFirewallIdFunctionsRoute,
  ApiFirewallsFirewallIdPolicyRoute: ApiFirewallsFirewallIdPolicyRoute,
  ApiFirewallsFirewallIdProofsRoute: ApiFirewallsFirewallIdProofsRoute,
  ApiFirewallsFirewallIdTargetsRoute: ApiFirewallsFirewallIdTargetsRoute,
  ApiOutcomesExecutionIdAnchorRoute: ApiOutcomesExecutionIdAnchorRoute,
  ApiOutcomesExecutionIdEvidenceRoute: ApiOutcomesExecutionIdEvidenceRoute,
  ApiOutcomesExecutionIdVerifyRoute: ApiOutcomesExecutionIdVerifyRoute,
  ApiProofsExecutionIdAnchorRoute: ApiProofsExecutionIdAnchorRoute,
  ApiProofsExecutionIdVerificationRoute: ApiProofsExecutionIdVerificationRoute,
  ApiProofsExecutionIdVerifyRoute: ApiProofsExecutionIdVerifyRoute,
  ApiV1AgentsAgentIdRoute: ApiV1AgentsAgentIdRoute,
  ApiV1ExecutionsExecutionIdRoute: ApiV1ExecutionsExecutionIdRoute,
  ApiV1WebhooksWebhookIdRoute: ApiV1WebhooksWebhookIdRoute,
  ApiAgentsAgentIdIndexRoute: ApiAgentsAgentIdIndexRoute,
  ApiFirewallsFirewallIdIndexRoute: ApiFirewallsFirewallIdIndexRoute,
  ApiOutcomesExecutionIdIndexRoute: ApiOutcomesExecutionIdIndexRoute,
  ApiProofsExecutionIdIndexRoute: ApiProofsExecutionIdIndexRoute,
  ApiV1AgentsIndexRoute: ApiV1AgentsIndexRoute,
  ApiV1FirewallsIndexRoute: ApiV1FirewallsIndexRoute,
  ApiV1WebhooksIndexRoute: ApiV1WebhooksIndexRoute,
  ApiV1FirewallsFirewallIdExecuteRoute: ApiV1FirewallsFirewallIdExecuteRoute,
  ApiV1FirewallsFirewallIdFunctionsRoute:
    ApiV1FirewallsFirewallIdFunctionsRoute,
  ApiV1FirewallsFirewallIdTargetsRoute: ApiV1FirewallsFirewallIdTargetsRoute,
  ApiV1OutcomesExecutionIdVerifyRoute: ApiV1OutcomesExecutionIdVerifyRoute,
  ApiV1ProofsExecutionIdVerifyRoute: ApiV1ProofsExecutionIdVerifyRoute,
  ApiV1FirewallsFirewallIdIndexRoute: ApiV1FirewallsFirewallIdIndexRoute,
  ApiV1OutcomesExecutionIdIndexRoute: ApiV1OutcomesExecutionIdIndexRoute,
  ApiV1ProofsExecutionIdIndexRoute: ApiV1ProofsExecutionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
